### ISSUE TITLE
MsgConnectEx are not compatible with client version 5517

### ISSUE THREAD

**Issue by MystCaster** [darkfoxdeveloper/FoxConquer5517#1]
Connection message are based on Patch 5017-5187 message structure.
Correct 5517 version message structure is the following :

| Offset | Data Type | Description | Example |
| ---|--- | ---| ---|
| 0 | UINT16 | Packet Length | 52 |
|2|UINT16|Packet Identifier|1055|
|4|UINT32|Client Identity|1000000|
|8|UINT32|Authentication Code|2|
|12|UINT32|Game Server Port|5816|
|16|UINT32|Facebook ID|0|
|20|CHAR[32]|Game Server IP Address|192.168.1.2|

Here is the fix : 
```
        public MsgConnectEx(RejectionType type)
            : base(12)
        {
            WriteHeader(12, PacketType.MSG_CONNECT_EX);
            Authentication = (uint)type;
        }
```
...
```
        public MsgConnectEx(uint identity, uint authentication, string ip, int port)
            : base(52)
        {
            WriteHeader(52, PacketType.MSG_CONNECT_EX);
            Identity = identity;
            Authentication = authentication;
            IPAddress = ip;
            Port = port;
        }
```
...
```
        public string IPAddress
        {
            get { return ReadString(32, 20); }
            set { WriteString(value, 32, 20); }
        }
```
The change is not important if you are using a conquer loader but if you are only using a patched client it will not work...

**Comment by darkfoxdeveloper** [comment]
First at all, thanks for your contribution, you can do a push request for this?

**Comment by MystCaster** [comment]
I can if you grant me access :)

**Comment by darkfoxdeveloper** [comment]
> I can if you grant me access :)

Of course, you are already a collaborator

**Comment by darkfoxdeveloper** [comment]
Nice work, thanks :)
